name: scikit-spatial

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 32
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        stage:
          [
            'lint_code',
            'lint_docs',
            'types',
            'readme',
            'doctests',
            'unit',
            'property',
            'docs',
          ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run test stage
        run: bash ci/scripts/run_stage.sh ${{ matrix.stage }} ${{ matrix.python-version }}

      - name: Upload coverage to Codecov
        env:
          STAGE: ${{ matrix.stage }}
          PYTHON_VERSION: ${{ matrix.python-version }}
        if: $STAGE == 'unit'
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          env_vars: PYTHON_VERSION
          fail_ci_if_error: true
          verbose: true
