name: scikit-spatial

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 32
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        stage:
          [
            "lint_code",
            "lint_docs",
            "types",
            "readme",
            "doctests",
            "unit",
            "property",
            "docs",
          ]

    env:
      PYTHON_VERSION: ${{ matrix.python-version }}
      STAGE: ${{ matrix.stage }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python $PYTHON_VERSION
        uses: actions/setup-python@v2
        with:
          python-version: $PYTHON_VERSION

      - name: Run test stage
        run: bash ci/scripts/run_stage.sh $STAGE $PYTHON_VERSION

